name: Time logging

on:
  issues:
    types: [labeled, unlabeled]

permissions:
  contents: read
  issues: write

jobs:
  time-logging:
    if: github.event.label.name == 'in progress'
    runs-on: ubuntu-latest
    environment: time-logging
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Update time log in issue
        id: update_time_log_in_issue
        uses: actions/github-script@v7
        with:
          script: |
            const main = require("./.github/workflows/scripts/time-logging/update-issue-body.js");
            main(github, context, core);
      - name: Update time remaining in project item
        if: github.event.action == 'unlabeled'
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.PERSONAL_ACCESS_TOKEN}}
          script: |
            const main = require("./.github/workflows/scripts/time-logging/update-time-remaining.js");
            main(github, context, {
              durationMinutes: ${{steps.update_time_log_in_issue.outputs.duration_minutes}},
              timeRemainingFieldId: "${{vars.TIME_REMAINING_FIELD_ID}}",
            });
