name: Add time log entry

on:
  issues:
    types: labeled

permissions:
  issues: write

jobs:
  add-time-log-entry:
    if: github.event.label.name == 'in progress'
    runs-on: ubuntu-latest
    steps:
      - name: Add time log entry to issue body
        uses: actions/github-script@v7
        with:
          script: |
            const now = new Date();
            const nowString = now.toLocaleString("sv-SE", {timeZone: "Europe/Amsterdam"}); // YYYY-MM-DD HH:MM:SS format

            const timeZoneOffset = new Date(now.toLocaleString("sv-SE", {timeZone: "Europe/Amsterdam"})) - now;
            const testDate = new Date(new Date("2025-07-06 13:00:00") - timeZoneOffset);
            console.log(testDate);
            console.log(testDate.toString());

            const newTimeLogEntry = `| ${nowString} |                     |          |`;
            const newIssueBody = context.payload.issue.body.replace(
              /(?<=## Time log.+\|)\n(?!\|)/ms,
              "$&" + newTimeLogEntry + "\n"
            );

            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue.number,
              body: newIssueBody
            });
