name: Add time log entry

on:
  issues:
    types: labeled

permissions:
  issues: write

jobs:
  add-time-log-entry:
    runs-on: ubuntu-latest
    steps:
      - name: Add time log entry to issue body
        uses: actions/github-script@v7
        with:
          script: |
            const now = new Date();
            const nowString = now.toLocaleString("sv-SE", {timeZone: "Europe/Amsterdam"}); // YYYY-MM-DD HH:MM:SS format

            console.log(nowString);
            console.log(now.toLocaleString("sv-SE"));
            console.log(new Date());

            const newTimeLogEntry = `| ${nowString} |                     |          |`;
            const newIssueBody = context.payload.issue.body.replace(
              /(?<=## Time log.+\|)\n(?!\|)/ms,
              "$&" + newTimeLogEntry + "\n"
            );

            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue.number,
              body: newIssueBody
            });
