name: Add time log
on:
    issues:
        types: labeled
jobs:
    add-time-log:
        runs-on: ubuntu-latest
        steps:
            - run: echo "${{github.event_name}}"
            - run: echo "${{github.event}}"
            - run: echo "${{github.event.label}}"
