name: Add time log

on:
    webhook:
        types:
            - projects_v2_status_update

jobs:
    add-time-log:
        runs-on: ubuntu-latest
        steps:
            - run: echo "${{github.event.projects_v2_status_update.status}}"
