name: Time logging

on:
  issues:
    types: [labeled, unlabeled]

permissions:
  issues: write

jobs:
  time-logging:
    if: github.event.label.name == 'in progress'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Update time log in issue
        uses: actions/github-script@v7
        with:
          script: |
            const main = require("./script.js")
            main(github, context);
